# Generated by Django 6.0.2 on 2026-03-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_buyerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='address',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
